"use client";
import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";
import { Appbar } from "./appbar";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, session }) {
  return (
    <html className="h-full bg-gray-50" lang="en">
      <body className="h-full">
        <SessionProvider session={session}>
          
          <div className={" h-screen"}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}


